name: LoRa Generate Arm from Bicep
on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
  BICEP_FOLDER: Template

jobs:
  build_and_save:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build Arm from Bicep
      run: |
        az bicep build --file ${{ env.BICEP_FOLDER }}/main.bicep
    - name: Archive generated JSON file 
      uses: actions/upload-artifact@v3
      with:
        name: arm-json
        path: ${{ env.BICEP_FOLDER }}/main.json
