name: Release

on:
  workflow_dispatch:

jobs:
  steps:
  - uses: docker/setup-buildx-action@v2
    id: buildx
    with:
      install: true
  - name: Build and push docker images
    run: |
      docker buildx build --rm -f "./LoRaEngine/modules/LoRaWanNetworkSrvModule/Dockerfile.amd64" -t "$ORGANISATION/lorawannetworksrvmodule:$version-amd64" --output type=image,push=true "."
    env:
      ORGANISATION: "ouphi"
      